name: Playwright demo tests
on:
  push:
  workflow_dispatch:
  schedule:
    # run 10 minutes past every 2nd hour
    - cron: '10 */2 * * *'
jobs:
  playwright-demo-node:
    name: Playwright version 1.23
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.23.0-focal
    # stop the job if it runs over 115 minutes
    # to prevent a hanging process from using CI minutes
    timeout-minutes: 115
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 10
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npx playwright test
      - name: Upload artifacts report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
      - name: Deploy Cypress report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: docs
